/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.example;

import org.example.Product;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

    Product obj = new Product("Pixel", 7, 12000, "google's phone"); 
     obj.displayProductdetails();
    }
}
